# Kubernetes Deployment Manifests for AthSys v2.1
# Deploy to enterprise Kubernetes clusters (EKS, AKE, GKE)

---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: athsys
  labels:
    name: athsys

---
# ConfigMap for application config
apiVersion: v1
kind: ConfigMap
metadata:
  name: athsys-config
  namespace: athsys
data:
  FLASK_ENV: "production"
  DEBUG: "False"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"
  RATELIMIT_ENABLED: "True"
  RATELIMIT_DEFAULT: "1000/hour"

---
# Secret for sensitive data
apiVersion: v1
kind: Secret
metadata:
  name: athsys-secrets
  namespace: athsys
type: Opaque
stringData:
  SECRET_KEY: "change-me-in-production"
  JWT_SECRET_KEY: "change-me-in-production"
  DB_PASSWORD: "change-me-in-production"
  REDIS_PASSWORD: "change-me-in-production"
  POSTGRES_PASSWORD: "change-me-in-production"

---
# PostgreSQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: athsys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: athsys_user
        - name: POSTGRES_DB
          value: athsys_db
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: POSTGRES_PASSWORD
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U athsys_user
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U athsys_user
          initialDelaySeconds: 10
          periodSeconds: 5
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "2"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc

---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: athsys
spec:
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP

---
# PostgreSQL PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: athsys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

---
# Redis Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: athsys
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7-alpine
        ports:
        - containerPort: 6379
        command:
        - redis-server
        - --requirepass
        - $(REDIS_PASSWORD)
        env:
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: REDIS_PASSWORD
        volumeMounts:
        - name: redis-storage
          mountPath: /data
        livenessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: redis-storage
        persistentVolumeClaim:
          claimName: redis-pvc

---
# Redis Service
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: athsys
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP

---
# Redis PersistentVolumeClaim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: athsys
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: athsys-backend
  namespace: athsys
  labels:
    app: athsys-backend
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: athsys-backend
  template:
    metadata:
      labels:
        app: athsys-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9090"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: athsys-backend
      containers:
      - name: backend
        image: athsys-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 9090
          name: metrics
        env:
        - name: FLASK_APP
          value: src/backend/app.py
        - name: DATABASE_URL
          value: "postgresql://athsys_user:$(DB_PASSWORD)@postgres:5432/athsys_db"
        - name: REDIS_URL
          value: "redis://:$(REDIS_PASSWORD)@redis:6379/0"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: SECRET_KEY
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: JWT_SECRET_KEY
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: DB_PASSWORD
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: athsys-secrets
              key: REDIS_PASSWORD
        envFrom:
        - configMapRef:
            name: athsys-config
        livenessProbe:
          httpGet:
            path: /live
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        volumeMounts:
        - name: logs
          mountPath: /app/logs
      volumes:
      - name: logs
        emptyDir: {}
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - athsys-backend
              topologyKey: kubernetes.io/hostname

---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: athsys-backend
  namespace: athsys
  labels:
    app: athsys-backend
spec:
  type: LoadBalancer
  selector:
    app: athsys-backend
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics

---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: athsys-backend
  namespace: athsys

---
# HorizontalPodAutoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: athsys-backend-hpa
  namespace: athsys
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: athsys-backend
  minReplicas: 3
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# NetworkPolicy
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: athsys-network-policy
  namespace: athsys
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: athsys
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: athsys
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 53  # DNS
